name: Trigger auto deployment for educational-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/educational-api-AutoDeployTrigger-59517e90-e96a-47b7-b4ef-008bb7a91ac0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EDUCATIONALAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EDUCATIONALAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EDUCATIONALAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: eduacr9303.azurecr.io
          registryUsername: ${{ secrets.EDUCATIONALAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EDUCATIONALAPI_REGISTRY_PASSWORD }}
          containerAppName: educational-api
          resourceGroup: educational-system-rg
          imageToBuild: eduacr9303.azurecr.io/educational-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


